In [1]:
texts = [
    "Apple Inc. is planning to open a new store in Paris next month.",
    "Microsoft Corporation announced a major acquisition yesterday.",
    "The Eiffel Tower, located in Paris, attracts millions of tourists annually.",
    "Elon Musk, the CEO of SpaceX, is known for his ambitious projects.",
    "Japan will host the Olympic Games in 2022."
]

labels = [
    ["B-org", "I-org", "O", "O", "O", "O", "O", "O", "O", "B-geo", "O", "B-time", "I-time"],
    ["B-org", "I-org", "O", "O", "O", "O","B-time"],
    ["O", "B-geo", "I-geo", "O", "O", "B-geo", "O", "O", "O", "O", "B-time"],
    ["B-person", "I-person", "O", "O", "O", "B-org", "O", "O", "O", "O", "O", "O"],
    ["B-geo", "O", "O", "O", "B-event", "I-event", "O", "B-time"]
]


In [2]:
import re

In [3]:
processed_texts = [re.sub(r'[^a-z0-9\s]', '', sentence.lower()) for sentence in texts]
processed_texts

['apple inc is planning to open a new store in paris next month',
 'microsoft corporation announced a major acquisition yesterday',
 'the eiffel tower located in paris attracts millions of tourists annually',
 'elon musk the ceo of spacex is known for his ambitious projects',
 'japan will host the olympic games in 2022']

In [4]:
processed_labels = [[re.sub(r'[^a-z0-9\s]', '', label.lower()) for label in sentence] for sentence in labels]
processed_labels

[['borg',
  'iorg',
  'o',
  'o',
  'o',
  'o',
  'o',
  'o',
  'o',
  'bgeo',
  'o',
  'btime',
  'itime'],
 ['borg', 'iorg', 'o', 'o', 'o', 'o', 'btime'],
 ['o', 'bgeo', 'igeo', 'o', 'o', 'bgeo', 'o', 'o', 'o', 'o', 'btime'],
 ['bperson', 'iperson', 'o', 'o', 'o', 'borg', 'o', 'o', 'o', 'o', 'o', 'o'],
 ['bgeo', 'o', 'o', 'o', 'bevent', 'ievent', 'o', 'btime']]

In [5]:
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences

2023-12-28 13:33:05.262384: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-12-28 13:33:05.327716: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-12-28 13:33:05.328591: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-12-28 13:33:06.382346: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [6]:
texts_tokenizer = Tokenizer()

In [7]:
texts_tokenizer.fit_on_texts(processed_texts)
texts_tokenizer.index_word

{1: 'in',
 2: 'the',
 3: 'is',
 4: 'a',
 5: 'paris',
 6: 'of',
 7: 'apple',
 8: 'inc',
 9: 'planning',
 10: 'to',
 11: 'open',
 12: 'new',
 13: 'store',
 14: 'next',
 15: 'month',
 16: 'microsoft',
 17: 'corporation',
 18: 'announced',
 19: 'major',
 20: 'acquisition',
 21: 'yesterday',
 22: 'eiffel',
 23: 'tower',
 24: 'located',
 25: 'attracts',
 26: 'millions',
 27: 'tourists',
 28: 'annually',
 29: 'elon',
 30: 'musk',
 31: 'ceo',
 32: 'spacex',
 33: 'known',
 34: 'for',
 35: 'his',
 36: 'ambitious',
 37: 'projects',
 38: 'japan',
 39: 'will',
 40: 'host',
 41: 'olympic',
 42: 'games',
 43: '2022'}

In [8]:
text_sequences = texts_tokenizer.texts_to_sequences(processed_texts)
text_sequences

[[7, 8, 3, 9, 10, 11, 4, 12, 13, 1, 5, 14, 15],
 [16, 17, 18, 4, 19, 20, 21],
 [2, 22, 23, 24, 1, 5, 25, 26, 6, 27, 28],
 [29, 30, 2, 31, 6, 32, 3, 33, 34, 35, 36, 37],
 [38, 39, 40, 2, 41, 42, 1, 43]]

In [9]:
vocab_size = len(texts_tokenizer.index_word) + 1
vocab_size

44

In [10]:
x = []
for i in text_sequences:
    x.append(len(i))
max_len_sequences = max(x)
x

[13, 7, 11, 12, 8]

In [11]:
padded_text_sequences = pad_sequences(sequences=text_sequences , maxlen=max_len_sequences , padding="post")
padded_text_sequences

array([[ 7,  8,  3,  9, 10, 11,  4, 12, 13,  1,  5, 14, 15],
       [16, 17, 18,  4, 19, 20, 21,  0,  0,  0,  0,  0,  0],
       [ 2, 22, 23, 24,  1,  5, 25, 26,  6, 27, 28,  0,  0],
       [29, 30,  2, 31,  6, 32,  3, 33, 34, 35, 36, 37,  0],
       [38, 39, 40,  2, 41, 42,  1, 43,  0,  0,  0,  0,  0]], dtype=int32)

In [12]:
flat_labels = [label for sublist in processed_labels for label in sublist]

In [13]:
label_mapping = {label: idx for idx, label in enumerate(set(flat_labels))}
label_mapping

{'bgeo': 0,
 'o': 1,
 'borg': 2,
 'bperson': 3,
 'btime': 4,
 'iorg': 5,
 'itime': 6,
 'bevent': 7,
 'ievent': 8,
 'iperson': 9,
 'igeo': 10}

In [14]:
labels_indices = [
    [label_mapping[label] for label in sentence] for sentence in processed_labels
]
labels_indices

[[2, 5, 1, 1, 1, 1, 1, 1, 1, 0, 1, 4, 6],
 [2, 5, 1, 1, 1, 1, 4],
 [1, 0, 10, 1, 1, 0, 1, 1, 1, 1, 4],
 [3, 9, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1],
 [0, 1, 1, 1, 7, 8, 1, 4]]

In [15]:
x 

[13, 7, 11, 12, 8]

In [16]:
y = []
for i in labels_indices:
    y.append(len(i))
max_len_sequences = max(y)
max_len_sequences

13

In [17]:
y

[13, 7, 11, 12, 8]

In [18]:
max_label_length = max(len(seq) for seq in labels_indices)
max_label_length

13

In [19]:
padded_label_sequences = pad_sequences(sequences=labels_indices , padding='post' , value=0 , maxlen=max_label_length)
padded_label_sequences

array([[ 2,  5,  1,  1,  1,  1,  1,  1,  1,  0,  1,  4,  6],
       [ 2,  5,  1,  1,  1,  1,  4,  0,  0,  0,  0,  0,  0],
       [ 1,  0, 10,  1,  1,  0,  1,  1,  1,  1,  4,  0,  0],
       [ 3,  9,  1,  1,  1,  2,  1,  1,  1,  1,  1,  1,  0],
       [ 0,  1,  1,  1,  7,  8,  1,  4,  0,  0,  0,  0,  0]], dtype=int32)

In [20]:
padded_label_sequences[0]

array([2, 5, 1, 1, 1, 1, 1, 1, 1, 0, 1, 4, 6], dtype=int32)

In [21]:
padded_text_sequences[0]

array([ 7,  8,  3,  9, 10, 11,  4, 12, 13,  1,  5, 14, 15], dtype=int32)

In [22]:
num_classes = len(label_mapping)
num_classes

11

In [23]:
import numpy as np
from keras.models import Sequential
from keras.layers import Embedding, LSTM, Dense , Bidirectional ,Dropout

In [24]:
model = Sequential([
    Embedding( input_dim=vocab_size , output_dim=50 , input_length=max_len_sequences),
    Bidirectional(LSTM(300,return_sequences=True)),
    Dropout(0.2),
    Bidirectional(LSTM(200,return_sequences=True)),
    Dropout(0.2),
    Bidirectional(LSTM(100,return_sequences=True)),
    Dropout(0.2),
    Dense( units=num_classes , activation="softmax")
])

model.compile(
    optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy']
)

In [25]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 13, 50)            2200      
                                                                 
 bidirectional (Bidirection  (None, 13, 600)           842400    
 al)                                                             
                                                                 
 dropout (Dropout)           (None, 13, 600)           0         
                                                                 
 bidirectional_1 (Bidirecti  (None, 13, 400)           1281600   
 onal)                                                           
                                                                 
 dropout_1 (Dropout)         (None, 13, 400)           0         
                                                                 
 bidirectional_2 (Bidirecti  (None, 13, 200)           4

In [26]:
X_train = padded_text_sequences
Y_train = padded_label_sequences

In [27]:
X_train 

array([[ 7,  8,  3,  9, 10, 11,  4, 12, 13,  1,  5, 14, 15],
       [16, 17, 18,  4, 19, 20, 21,  0,  0,  0,  0,  0,  0],
       [ 2, 22, 23, 24,  1,  5, 25, 26,  6, 27, 28,  0,  0],
       [29, 30,  2, 31,  6, 32,  3, 33, 34, 35, 36, 37,  0],
       [38, 39, 40,  2, 41, 42,  1, 43,  0,  0,  0,  0,  0]], dtype=int32)

In [28]:
Y_train

array([[ 2,  5,  1,  1,  1,  1,  1,  1,  1,  0,  1,  4,  6],
       [ 2,  5,  1,  1,  1,  1,  4,  0,  0,  0,  0,  0,  0],
       [ 1,  0, 10,  1,  1,  0,  1,  1,  1,  1,  4,  0,  0],
       [ 3,  9,  1,  1,  1,  2,  1,  1,  1,  1,  1,  1,  0],
       [ 0,  1,  1,  1,  7,  8,  1,  4,  0,  0,  0,  0,  0]], dtype=int32)

In [29]:
# Y_train = np.eye(num_classes)[Y_train]

In [30]:
model.fit(X_train, Y_train, epochs=50)

Epoch 1/50


1/1 [==============================] - 13s 13s/step - loss: 2.4008 - accuracy: 0.0154
Epoch 2/50
1/1 [==============================] - 0s 166ms/step - loss: 2.3602 - accuracy: 0.6462
Epoch 3/50
1/1 [==============================] - 0s 188ms/step - loss: 2.3008 - accuracy: 0.6308
Epoch 4/50
1/1 [==============================] - 0s 147ms/step - loss: 2.1878 - accuracy: 0.6308
Epoch 5/50
1/1 [==============================] - 0s 135ms/step - loss: 1.9812 - accuracy: 0.6000
Epoch 6/50
1/1 [==============================] - 0s 148ms/step - loss: 1.6452 - accuracy: 0.5692
Epoch 7/50
1/1 [==============================] - 0s 148ms/step - loss: 1.4336 - accuracy: 0.5846
Epoch 8/50
1/1 [==============================] - 0s 136ms/step - loss: 1.5523 - accuracy: 0.6308
Epoch 9/50
1/1 [==============================] - 0s 125ms/step - loss: 1.5312 - accuracy: 0.6308
Epoch 10/50
1/1 [==============================] - 0s 139ms/step - loss: 1.4319 - accuracy: 0.6154
Epoch 11/50
1/1 [==============

In [31]:
tokenizer = Tokenizer()

In [38]:
test_texts = [
    "Apple Inc. is planning to open a new store in Paris next month.",
    "Microsoft Corporation announced a major acquisition yesterday.",
    "The Eiffel Tower, located in Paris, attracts millions of tourists annually.",
    "Elon Musk, the CEO of SpaceX, is known for his ambitious projects.",
    "Japan will host the Olympic Games in 2022."
]

test_sequences = texts_tokenizer.texts_to_sequences(test_texts)
test_sequences_padded = pad_sequences(test_sequences, maxlen=max_len_sequences, padding='post')

predictions = model.predict(test_sequences_padded)
print("\npredictions :",predictions)

predicted_labels = np.argmax(predictions, axis=-1)
print("\npredicted_labels :",predicted_labels)

reverse_label_mapping = {index: label for label,index in label_mapping.items()}
print("\nreverse_label_mapping :",reverse_label_mapping)

predicted_label_mapped = [[reverse_label_mapping[index] for index in sequence] for sequence in predicted_labels]
print("\n\npredicted_label_mapped :",predicted_label_mapped)

1/1 [==============================] - 0s 54ms/step

predictions : [[[1.55327737e-01 2.74194032e-01 2.43364587e-01 6.16074279e-02
   4.54832800e-03 1.30341396e-01 5.57034789e-03 1.23870028e-02
   4.41347435e-03 6.30896762e-02 4.51559797e-02]
  [1.09702691e-01 5.64450383e-01 1.54854849e-01 1.65538471e-02
   2.01715040e-03 8.18842277e-02 2.02198373e-03 8.27179849e-03
   2.24882015e-03 2.74631884e-02 3.05310413e-02]
  [6.89294040e-02 7.82149613e-01 8.24826509e-02 3.35199502e-03
   8.00034439e-04 3.37042212e-02 6.68699562e-04 4.35456960e-03
   1.03080668e-03 8.23338982e-03 1.42947007e-02]
  [4.77131344e-02 8.82050574e-01 4.50640768e-02 7.46807840e-04
   3.75271164e-04 1.21745383e-02 2.67904834e-04 2.37359572e-03
   5.63889451e-04 2.56965542e-03 6.10059220e-03]
  [3.89891304e-02 9.23956275e-01 2.60890294e-02 2.18456626e-04
   2.42380178e-04 4.62496048e-03 1.50444321e-04 1.58543128e-03
   3.94907460e-04 9.87974112e-04 2.76097003e-03]
  [3.75198461e-02 9.41299319e-01 1.51397465e-02 8.41194487

In [39]:
predicted_label_mapped[0]

['o', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'btime', 'itime']

In [33]:
predicted_labels

array([[1, 1, 1, 1, 1, 4, 0, 0, 0, 0, 0, 0, 0]])

In [34]:
predictions[0][0]

array([0.18171844, 0.32799542, 0.13778247, 0.00915144, 0.00800748,
       0.21394183, 0.00103516, 0.05573627, 0.02062828, 0.00695129,
       0.03705184], dtype=float32)

In [35]:
len(predictions)

1

In [36]:
len(predictions[0])

13

In [37]:
len(predictions[0][0])

11