In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_iris

In [2]:
iris = load_iris()
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [3]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [4]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(iris.data , iris.target , test_size=0.3)

In [5]:
def get_score(model , X_train , X_test , y_train , y_test):
    model.fit (X_train, y_train)
    return model.score(X_test , y_test)

KFold

In [6]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3 , shuffle=True)
kf

KFold(n_splits=3, random_state=None, shuffle=True)

In [7]:
for train_index , test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index , test_index)

[1 3 4 5 6 8] [0 2 7]
[0 1 2 5 6 7] [3 4 8]
[0 2 3 4 7 8] [1 5 6]


Stratified KFold

In [27]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=5)

In [34]:
model_lr = []
model_svm = []
model_rf = []

for train_index , test_index in kf.split(iris.data):
    X_train = iris.data[train_index]
    X_test = iris.data[test_index]
    y_train = iris.target[train_index]
    y_test = iris.target[test_index]
    
    model_lr.append(get_score( LogisticRegression() , X_train , X_test , y_train , y_test))
    model_svm.append(get_score( SVC() , X_train , X_test , y_train , y_test))
    model_rf.append(get_score( RandomForestClassifier(n_estimators=50) , X_train , X_test , y_train , y_test))

/home/adarsh/.local/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/adarsh/.local/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regressi

In [10]:
model_lr

[0.96, 0.98, 0.96]

In [11]:
model_svm

[0.96, 0.98, 0.96]

In [12]:
model_rf

[0.96, 0.94, 0.94]

In [15]:
model_lr

[1.0, 0.94, 0.92]

In [16]:
model_svm

[1.0, 0.96, 0.94]

In [18]:
model_rf

[1.0, 0.92, 0.92]

Cross Val Score

In [36]:
from sklearn.model_selection import cross_val_score

In [38]:
cross_val_score(LogisticRegression() , iris.data , iris.target)

/home/adarsh/.local/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [39]:
cross_val_score(SVC() , iris.data , iris.target)

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [41]:
cross_val_score(RandomForestClassifier() , iris.data , iris.target)


array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])

In [42]:
cross_val_score(RandomForestClassifier(n_estimators=40) , iris.data , iris.target)


array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])

In [43]:
cross_val_score(RandomForestClassifier(n_estimators=50) , iris.data , iris.target)


array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ])

In [44]:
cross_val_score(RandomForestClassifier(n_estimators=30) , iris.data , iris.target)


array([0.96666667, 0.96666667, 0.9       , 0.9       , 1.        ])

In [45]:
cross_val_score(RandomForestClassifier(n_estimators=20) , iris.data , iris.target)


array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ])